name: test-windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      notify_debug:
        description: "Enable debug logging"
        type: choice
        options:
          - "No"
          - "Yes"
        default: "No"
      tags:
        description: "Go tags"
        type: string
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-windows:
    name: test-windows
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - windows-2019
        go:
          # - "~1.22.9"
          - "~1.23.3"

    runs-on: ${{ matrix.runner }}

    steps:
      - name: If Windows, set git to use LF
        if: contains(matrix.runner, 'windows')
        # Without this, the Windows checkout will happen with CRLF line
        # endings, which is fine for the source code but messes up tests
        # that depend on data on disk being as expected. Ideally, those
        # tests should be fixed, but not today.
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: |
          go version
          go env
          go get -v ./...

      - name: Run tests
        shell: bash
        run: |
          if [[ "${{ inputs.notify_debug }}" =~ Yes ]]; then
            export NOTIFY_DEBUG=1
          fi
          export TAGS="${{ inputs.tags }}"
          go test -v -tags "${TAGS}" ./...
